server:
  port: 8086
  context-path: /shop
spring:
  datasource:
    url: jdbc:mysql://106.12.197.29:3306/shop?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=GMT
    username: root
    password: XuLiZhi@9418
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true