server:
  port: 8088
  context-path: /shop
spring:
  datasource:
    url: jdbc:mysql://106.12.197.29:3306/shop?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
wechat:
  mpAppId: wx2c9123db004a728f
  mpAppSecret: 7d8df054212596d59283a65e1aee3543

projectUrl:
  wechatMpAuthorize: http://xulizhi.natapp1.cc
  wechatOpenAuthorize: http://xulizhi.natapp1.cc
  shop: http://xulizhi.natapp1.cc