server:
  port: 8086
  context-path: /shop
spring:
  datasource:
    url: jdbc:mysql://106.12.197.29:3306/shop?characterEncoding=utf-8&useSSL=false
    username: root
    password: XuLiZhi@9418
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true